name: RegenStick
version: 1.0
main: com.afelia.regenstick.RegenStick
author: Elias
description: A Minecraft plugin that provides a regeneration stick.
api-version: '1.20' # Adjust this according to the version of Bukkit/Spigot you're using

commands:
  giveregenstick:
    description: Gives the player a regeneration stick.
    usage: /giveregenstick
    permission: regenstick.give

  giveplayerregenstick:
    description: Gives a player a regeneration stick.
    usage: /giveplayerregenstick <player>
    permission: regenstick.giveplayer
